version: '3.5'

services:

    projectname_php:
        container_name: projectname_php
        hostname: projectname_php
        build: ./docker/php
        user: root
        volumes:
            - ./app:/var/www/html
            - ./docker:/var/docker/
            - ./docker/php/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
            - ./docker/php/php-client.ini:/usr/local/etc/php/conf.d/php-client.ini
            - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
        external_links:
            - mailcatcher
            - redis
            - nginx-proxy
        links:
            - projectname_mysql
        networks:
            - dev_env
            - projectname_env
        environment:
            - VIRTUAL_HOST=projectname.local # For reverse-proxy

    projectname_mysql:
        container_name: projectname_mysql
        image: mysql
        hostname: projectname_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=projectname_01
        volumes:
            # - ./docker/database:/docker-entrypoint-initdb.d # docker output for running mysqls
            - ./docker/var/lib/mysql:/var/lib/mysql # databases files
        networks:
            - projectname_env

networks:
    dev_env:
        external: true
    projectname_env:
        name: projectname_env
